'use strict';function _classCallCheck(a,c){if(!(a instanceof c))throw new TypeError("Cannot call a class as a function");}function _defineProperties(a,c){for(var b=0;b<c.length;b++){var d=c[b];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}function _createClass(a,c,b){c&&_defineProperties(a.prototype,c);b&&_defineProperties(a,b);return a}
function _slicedToArray(a,c){return _arrayWithHoles(a)||_iterableToArrayLimit(a,c)||_unsupportedIterableToArray(a,c)||_nonIterableRest()}function _toConsumableArray(a){return _arrayWithoutHoles(a)||_iterableToArray(a)||_unsupportedIterableToArray(a)||_nonIterableSpread()}function _arrayWithoutHoles(a){if(Array.isArray(a))return _arrayLikeToArray(a)}function _arrayWithHoles(a){if(Array.isArray(a))return a}
function _iterableToArray(a){if("undefined"!==typeof Symbol&&Symbol.iterator in Object(a))return Array.from(a)}function _iterableToArrayLimit(a,c){if("undefined"!==typeof Symbol&&Symbol.iterator in Object(a)){var b=[],d=!0,f=!1,g=void 0;try{for(var e=a[Symbol.iterator](),h;!(d=(h=e.next()).done)&&(b.push(h.value),!c||b.length!==c);d=!0);}catch(k){f=!0,g=k}finally{try{if(!d&&null!=e["return"])e["return"]()}finally{if(f)throw g;}}return b}}
function _unsupportedIterableToArray(a,c){if(a){if("string"===typeof a)return _arrayLikeToArray(a,c);var b=Object.prototype.toString.call(a).slice(8,-1);"Object"===b&&a.constructor&&(b=a.constructor.name);if("Map"===b||"Set"===b)return Array.from(b);if("Arguments"===b||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(b))return _arrayLikeToArray(a,c)}}function _arrayLikeToArray(a,c){if(null==c||c>a.length)c=a.length;for(var b=0,d=Array(c);b<c;b++)d[b]=a[b];return d}
function _nonIterableSpread(){throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");}function _nonIterableRest(){throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");}
var Subject=function(){function a(a){return!this.done&&Object.prototype.hasOwnProperty.call(this.subject,a)&&"function"===typeof this.subject[a]}var c=new WeakMap;return function(){function b(a){_classCallCheck(this,b);Object.defineProperties(this,{subject:{value:a}});c.set(this,!1)}_createClass(b,[{key:"next",value:function(c,b){if(a.call(this,c))this.subject[c](b)}},{key:"complete",value:function(){c.set(this,!0)}},{key:"delete",value:function(c){a.call(this,c)&&delete this.subject[c]}},{key:"done",
get:function(){return c.get(this)}}]);return b}()}(),Subscription=function(){function a(c,b){_classCallCheck(this,a);Object.defineProperties(this,{id:{value:c},publisher:{value:b}})}_createClass(a,[{key:"unsubscribe",value:function(a){this.publisher.unsubscribe(this.id,a)}}]);return a}(),Publisher=function(){var a=new WeakMap,c=new WeakMap;return function(){function b(){_classCallCheck(this,b);a.set(this,1);c.set(this,new Map)}_createClass(b,[{key:"subscribe",value:function(b){b=new Subject(b);var d=
a.get(this);a.set(this,d+1);c.get(this).set(d,b);return new Subscription(d,this)}},{key:"unsubscribe",value:function(a,b){var d=c.get(this);if(d.has(a)){var e=d.get(a);if(b&&"function"===typeof e["delete"])e["delete"](b);b&&Object.keys(e.subject).length||("function"===typeof e.complete&&e.complete(),d["delete"](a))}}},{key:"set",value:function(a,b){var d=c.get(this);_toConsumableArray(d).forEach(function(c){_slicedToArray(c,2)[1].next(a,b)});this[a]=b;return this}}]);return b}()}();
module.exports=Publisher
